global:
  timezone: Asia/Tokyo
  cache:
    base: /tmp
  log:
    level: info

plugins:
  - module: SubscriptionFeed
    config:
      feeds:
        - http://id774.net/blog/feed/

  - module: FilterIgnore
    config:
      exclude:
        - hoge
        - fuga

  - module: PublishHatenaBookmark
    config:
      username: your_hatena_id
      password: your_password
      db: bookmark.db

