global:
  timezone: Asia/Tokyo
  cache:
    base: /tmp
  log:
    level: info

plugins:
  module: AutoBookmark
  config:
    username: username
    passowrd: password
    db: bookmark.db
    feeds:
      - aaa
      - bbb
      - ccc
    exclude:
      - ddd
      - eee
      - fff

